### ISSUE TITLE
Add clickable link to each stub

### ISSUE THREAD

**Issue by mattfrear** [getsandbox/feedback#1]
This is a nice to have. 

On the Sandbox details page.
It would be useful to be able to click a link in the browser which opens my route (and maybe with any defaults for required arguments) so that I can quickly hit a route in my browser. And share a route with a colleague.

At the moment I have to click the link to xxx.getsandbox.com and open that in a new tab, and then copy the /api/myendpoint bit from the Sandbox details page. It would be nice to not have to do this copy-pasting and just have one fully formed url in the details bit of each route.

**Comment by nhoughto** [comment]
Certainly possible to have a quick link that opens a new tab, I have had this problem myself.

GETs are easy obviously, any other verb is not possible, what would your expected behaviour be for say a POST? Or are you just looking to get a copy of the full testable URL?

**Comment by mattfrear** [comment]
A copy of the full testable URL is all I want - if it's clickable on GETS then all the better.

**Comment by nhoughto** [comment]
Copy URL link now available for each route in the route overview page.

Let us know if it suits, the flash dependency is a bit crap but nicest way to do it.
![screen shot 2015-05-07 at 10 30 46 pm](https://cloud.githubusercontent.com/assets/1276450/7515248/c7747b78-f508-11e4-903a-43034139986c.png)

**Comment by mattfrear** [comment]
Thanks, that will be useful and is an improvement :+1: 

Perhaps though, more useful would just be a plain old link with text something like "Go ->" which I could click to open in a new tab, or right click and copy address if I so choose to do.

With the copy link which you have implemented it's still a few steps to open in my browser - click copy, open a new tab, click address bar, paste link.

**Comment by nhoughto** [comment]
Tweaked the implementation, now its just a plain <a> tag, no fancy copying. So for GETs you can click, others you can copy as per normal.

**Comment by mattfrear** [comment]
Thanks Nick. One small issue - when I click it, two things happen - the route opens in a new tab (yay!) but it also expands the routing box. You may not want it to do that as it does slightly spoil (IMO) the very slick UI you guys have.

**Comment by nhoughto** [comment]
Ah yes good point, easy fix. ta

**Comment by nhoughto** [comment]
Deployed.

**Comment by mattfrear** [comment]
Looks good, thanks (y)
