### ISSUE TITLE
The "Coding" tab renders poorly when screen width is 1920/2

### ISSUE THREAD

**Issue by sparksis** [getsandbox/feedback#13]
When pinning the browser to either side of the screen on a 1920x1080 monitor the coding tab does not render correctly.

The following screenshot is with a Chrome browser window pinned to the left side of the monitor on a 1920x1080 monitor.  No extensions or plugins are installed.  OS: Fedora (though I've noticed this on Windows as well).

![screenshot from 2017-05-06 17-18-39](https://cloud.githubusercontent.com/assets/1209861/25776607/1925a63e-3280-11e7-9a77-f631a27f1412.png)

**Comment by nhoughto** [comment]
Yep that looks terrible at that breakpoint! We will fix it thanks 👍🏼

**Comment by nhoughto** [comment]
Thanks for the feedback, simple fixed is working its way through CI.
