### ISSUE TITLE
Alternative ports

### ISSUE THREAD

**Issue by sfmwright** [getsandbox/feedback#17]
The JMS interface allows the listening port to be specified. Any chance that this could also be allowed for HTTP/HTTPS? Specifically, port 8080 is commonly used as an alternative to port 80 for HTTP. Would it be possible to also listen on port 8080 for HTTP?

Thanks
Steve

**Comment by nhoughto** [comment]
For the runtime, server or cloud product?

The cloud version (getsandbox.com) is on both 80/443 for http/https. We don't plan to support 8080 for cloud but the server and runtime product allow you to config the port already.

**Comment by sfmwright** [comment]
Thanks for the fast response. I was referring to the cloud product.  Good to know that it is possible with the server product, however the cloud hosted solution suits my use case better.

I'm dealing with a legacy client that is hardcoded to port 8080 :-) Deploying NGINX locally in reverse proxy mode handily gets around the issue.
