### ISSUE TITLE
RAML 1.0 Support

### ISSUE THREAD

**Issue by dylan-asos** [getsandbox/feedback#18]
Hi, 

I'm trying to create a sandbox based on a RAML 1.0 specification, which is failing with the following message

![raml-sandbox](https://user-images.githubusercontent.com/16137664/33836463-63cccdea-de81-11e7-9276-3e106b5b3b93.png)

I notice the post is sending RAML_V08, is 1.0 not currently supported?

![v08-raml](https://user-images.githubusercontent.com/16137664/33836566-a4240944-de81-11e7-9f35-3790e57411dc.png)

Couple of points on the back of that, 

1) The error message isn't particularly helpful - something a bit more specific regarding the version incompatibility would've helped our users

2) Any plans to support 1.0 in the near future?

Thanks

**Comment by nhoughto** [comment]
You are right, the error messages sucks, it should have more details i'll raise a bug to see why its not giving you a better message.

We don't have good RAML 1.0 support at the moment, there are lots of weird edge-cases. It is on the backlog, so can be prioritised. You would be better off converting & flattening from RAML 1.0 to OAS 2 and then importing that. The RAML community is in flux at the moment as they seem to be working together with Swagger towards OAS 3, so will RAML live on? It might not be worth our time.. either way to use RAML 1.0:

Steps:
- Take raw (unflattened) RAML 0.8/1.0 directory / zip file
- Apply RAML to Swagger / OAS 2 conversion via suggested library (https://github.com/mulesoft/oas-raml-converter)
- Import generated OAS 2 JSON

**Comment by dylan-asos** [comment]
OK, will do - thanks for the feedback
