### ISSUE TITLE
Not able to create state

### ISSUE THREAD

**Issue by shobero** [getsandbox/feedback#20]
whenever i am trying to create states using example given in below link https://getsandbox.com/docs/stateful-responses, its giving below response 
 "errors": [
    {
      "message": "Runtime failure",
      "detailedMessage": "No body has been set in route, you must call one of .json(), .send(), .render() etc"
    }
  ]

**Comment by nhoughto** [comment]
Forgot that this is still open, can't repro this it so closing.
