### ISSUE TITLE
Not able to clone/move stored State-full responses

### ISSUE THREAD

**Issue by Elangopalakrishnan** [getsandbox/feedback#21]
Hi all,

I have created one Endpoint and had many routes under that.
And I have created some stateful responses in that Endpoint.

I tried to move endpoint routes to a new endpoint.
After moving to the new endpoint and **I checked stateful response not there in the new endpoint.**

Do i need to create again??/
Or is there any way to clone stateful responses ???

Thanks in advance!
Elango

**Comment by nhoughto** [comment]
If I’m understanding you correctly, this is by design. Each sandbox has its own separate state even if it’s cloned. That way definitions can be shared but state be different.

Is that the behavior you are seeing?

**Comment by Elangopalakrishnan** [comment]
Yes, Apologies for very late reply, But i'm looking same feature, if it is possible to copy store stateful responses from one route to another.

**Comment by nhoughto** [comment]
State is shared between all routes of a given sandbox, but isn't copied/shared between sandbox instances.
