### ISSUE TITLE
ECMAScript 2019 / ES10 Support (alpha)

### ISSUE THREAD

**Issue by xviuda-rhm** [getsandbox/feedback#23]
You released the V3 alpha a month ago for the saas version. 
Will there be a run-time version?
I couldn't find a branch in your GitHub repo with the changes to the run-time.

**Comment by nhoughto** [comment]
Good point, we have it in a separate repo at the moment, now it’s alpha we can make it public and start working towards proper GA. I’ll aim to set it up this week 👍🏼

**Comment by xviuda-rhm** [comment]
@nhoughto Cool, can you let me know when you have done this.

**Comment by nhoughto** [comment]
FYI still working on this, packaging is proving little more complicated than expected.. few more days

**Comment by nhoughto** [comment]
Haven’t forgotten about this 👍🏼

**Comment by nhoughto** [comment]
Still chipping away at this, final bit of polish going on

**Comment by nhoughto** [comment]
https://github.com/getsandbox/worker-cli/
