### ISSUE TITLE
Incorrect display of the "bigint" JSON-property in the "Console / Request Body"

### ISSUE THREAD

**Issue by a110ut** [getsandbox/feedback#24]
Found small bug related to display large numbers in "Console / Request Body".

The situation shown in screenshot:
https://i.imgur.com/euyL843.png

376944461065000000**1** - is the correct value.

PS: Thank you for a great app

**Comment by nhoughto** [comment]
That is very weird, let me see..

**Comment by nhoughto** [comment]
Ah this must be overflowing javascript/json number length and being truncated, if you try the same in chrome dev console it will show the same:

```
var x = {id: 3769444610650000001}
undefined
x
Object { id: 3769444610650000000 }
```

Bit more detail here: https://stackoverflow.com/questions/13502398/json-integers-limit-on-size

Not much we can do about this I don't think, seems like you will run up against other problems using these values anyway (chrome/v8/others) will handle it the same way as we are, likely best to make it a string and avoid the whole mess? 🤔
