### ISSUE TITLE
Handling base64 in sandbox

### ISSUE THREAD

**Issue by Elangopalakrishnan** [getsandbox/feedback#26]
Hi Team,

Hope you are doing well, 

I have one quick question/may be doubt as I'm not much familiar with java script.

We are using get Sandbox, 

I have come across one scenario where I will send base64 string(this will be dynamic) to Sandbox endpoint and I would need to decode that and I need to respond back different response status based on decoded value.

I tried below code, 

Var decodedString = atob("base64") ;

Var decodedString1 = Buffer.from(obj,"base64").toString();

But Sandbox throwing err, 

Detailed message : atob and buffer are not defined in main. Js,

Do we need to import any libraries, How do we import into cloud Sandbox, 

Can you please help me with this?

Regards, 
Elango

**Comment by nhoughto** [comment]
answered via email
