### ISSUE TITLE
Sandbox not accepting all responses and models defined in the OpenApi File.

### ISSUE THREAD

**Issue by mh-spillai** [getsandbox/feedback#27]
Sandbox not accepting all responses and models defined in the OpenApi File.

Open API file:-
[inventory.zip](https://github.com/getsandbox/feedback/files/5814709/inventory.zip)

This API has two endpoints GET inventory with 200,400 responses defined and for POST inventory 201,409,400 responses.
But after uploading to sandbox it only has 200 and 201 responses respectively for GET and POST.

![sandbox screenshot](https://user-images.githubusercontent.com/75423468/104595213-448c5f80-5698-11eb-8729-a1deb1845ab3.PNG)

The actual response of GET inventory:-
![image](https://user-images.githubusercontent.com/75423468/104598137-3a6c6000-569c-11eb-9137-12c88cf20902.png)

Response from the sandbox:-
![image](https://user-images.githubusercontent.com/75423468/104598454-9c2cca00-569c-11eb-88ca-90d85e4257c2.png)

**Comment by nhoughto** [comment]
thanks for the example, will continue on email.
