### ISSUE TITLE
Support for RAML

### ISSUE THREAD

**Issue by mbadran** [getsandbox/feedback#3]
Hi,

Do you plan to support the [RAML](http://raml.org/) (RESTful API Modeling Language) standard?

If so, a timeline would be great.

**Comment by nhoughto** [comment]
Hey

Yep plan to support it, it is on the list, will bump it up now that someone is interested.

Timeline would be measured in weeks, no firm date yet though.

Thanks for the feedback.

**Comment by nhoughto** [comment]
Hey

RAML support is in testing at the moment, would be great to test it out with some real life RAMLs, can you send your most complicated file to hello@getsandbox.com?

It obviously needs to be flattened into one file, can use something like this to do it:
https://github.com/joeledwards/node-flat-raml

**Comment by nhoughto** [comment]
Hey

RAML v0.8 support was just pushed live. Let us know how you go.
