### ISSUE TITLE
cannot connect sandbox to desired github repo

### ISSUE THREAD

**Issue by blech75** [getsandbox/feedback#5]
i'm trying to connect a sandbox to a github repo, but i can't connect it because the repo i want to use is not listed on the external repo page. it seems only the first 30 repos are listed without 1) any note that this is not the complete list (leading to confusion), and 2) any ability to select a repo not in the first 30. both issues should be fixed.

possible ways to address this:

* add a "load more repos" button that, when clicked, will append the next set to the list
* add text input to allow searching/filtering the entire list of repos available
* (something else?)

(note: i have no idea what the API limitations are for retrieving the list of available repos.)

aside from my personal repos, i belong to a few organizations with lots of repos. i can't imagine i'm the only one with this situation.

**also, a minor bug with the UI:** the incorrect cursor (the i-beam text select cursor) is displayed when hovering over the link to select a repo. instead, it should display a `pointer`. (that link is an `a` element without an `href` attribute, a common pattern in angular apps).

**Comment by nhoughto** [comment]
Hey

We don't have more than 30 on our github account so have never encountered the problem, you are correct though i'm sure it is a common use case, thanks for the feedback. It is possibly a limitation of the github API. We will look into it.

In terms of a solution, possible a search style interface would work best, if you have many repos paging through them could get annoying..

**Comment by nhoughto** [comment]
Pushed a change to list all your repositories, github API doesn't support searching on repos you have access to, only your repos or repos generally so no good. Let me know if it suits.

Fixed the cursor problem too.

Thanks for the feedback.

**Comment by blech75** [comment]
thanks for the quick turnaround on this. it now works satisfactorily. i was able to successfully sync the repo.

(closing issue)
