### ISSUE TITLE
Integration with Public API catalog

### ISSUE THREAD

**Issue by IvanGoncharov** [getsandbox/feedback#6]
Hi,

I'm working on project called "APIs.guru", idea is to create "Wikipedia for REST APIs".
It's implemented as Github [repo](https://github.com/APIs-guru/api-models) with Swagger 2.0 models inside.
All models are converted from official sources(Google Discovery, SwaggerUI, Apigee consoles, ...) and kept in sync with original specs. 
Idea is to provide content which will allow 3rd-party services to automatically integrate APIs.

I'm working together with @bobby-brennan from LucyBot, and he made [AnyAPI](https://any-api.com/) portal which visualise all APIs from my collection. And right now, we are looking for other projects which can benefit from similar integration.

You can allow user to create sandboxes for public APIs for integration testing or just as showcase for your service.

**Comment by nhoughto** [comment]
Hey

Interesting project, when you 'try' and api at the moment where do the requests go? To the actual production API?

The idea with being able to import a definition like Swagger is that users can quickly spin up a stub for purposes such as integration testing. This is really important for 1st part APIs that are either unavailable or incomplete, for public APIs i'm not sure there is the same need (they often have test APIs or test keys). Will discuss it internally and see if we think we can add value.

Thanks for the note!

**Comment by IvanGoncharov** [comment]
Hi @nhoughto 

>Interesting project, when you 'try' and api at the moment where do the requests go? To the actual production API?

You probably asking about `any-api.com` portal, in that case it's yes.
One thing to note: `APIs.guru` is separate project and `any-api.com` is just one of platforms integrated with it. Right now we have integration in process with [SDKs.io](https://sdks.io) and [Corezoid](https://www.corezoid.com/). So main idea is that `APIs.guru` is just a catalog with access through it own REST API, and 3rd-party companies could use it for any purpose. Including creating websites with API catalog similar to `any-api.com`.

>This is really important for 1st part APIs that are either unavailable or incomplete, for public APIs i'm not sure there is the same need (they often have test APIs or test keys).

Yes at the moment we focused only on public APIs. And current goal is to integrate as much as possible platforms around catalog. It should motivate API owners to contribute/maintain specs for their APIs.
You can think about it like having public repo on Github, and having free access to tools like TravisCI, Coveralls and many others. At the same time you can offer some paid services to both API owner and API client without need to setup anything.

>Will discuss it internally and see if we think we can add value.

If you want I can make short presentation over Skype, and also answer all your question.
My email: ivan.goncharov.ua@gmail.com
Skype: ivangon4arov
Time zone: UTC+3
