### ISSUE TITLE
Can't define route with querystring

### ISSUE THREAD

**Issue by mattfrear** [getsandbox/feedback#7]
How on earth can I define a route with a querystring in it? I've wasted hours on trial and error testing trying to get this working.

This doesn't work:
Sandbox.define("/api/v1/validatesubscription?subscriptionId={subscriptionId}&country={country}", "GET", api.getApiValidateSubscription);

It appears to work from the sandbox detail page. I can see my desired response. But then when I try and hit my API at api/v1/validatesubscription?subscriptionId=1&country=GB I get 

{"errors":[{"message":"Invalid route"}]}

This works:
Sandbox.define("/api/v1/validatesubscription/{subscriptionId}/{country}", "GET", api.getApiValidateSubscription);

But I don't want that.

Your API doc page doesn't have a decent example using the querystring.
https://getsandbox.com/docs/sandbox-api

M

**Comment by drewstewart** [comment]
Hi Matt,

Query string parameters are available to your script on the req.query object. Theres an example here https://getsandbox.com/docs/request-handling.

To solve for your problem I would do:

Sandbox.define("/api/v1/validatesubscription", "GET", function(req,res) {
  // access query string parameters
  var subscriptionId = req.query.subscriptionId;
  var country = req.query.country;
});

Cheers,

Andrew.

**Comment by mattfrear** [comment]
Ah thanks. The mistake I made was thinking I had to explicitly specify
querystring parameters. Yes I saw that page in the doco too.

Thanks

-- 
*Matt Frear*
matt.frear@gmail.com
