### ISSUE TITLE
Response state error

### ISSUE THREAD

**Issue by ikopytko** [getsandbox/feedback#8]
After I import simple swagger definition ( /api/Page?token={query} , token is required ), next code generated
```
req.checkQuery('token', 'Invalid query parameter').notEmpty();
if (req.validationErrors()) {
    return res.json(400, req.validationErrorsJson());
}
res.status(200);
res.json({});
```

When I call endpoint for the first time with any parameners, the response was 200, next without parameter  - 400. Everything looks good. But next response with parameter give me the same 400 error. 
If I call method without parameter several times, number of the errors in output is growing. Ex:
```
{
  "message" : "Request has errors",
  "errors" : [ {
    "param" : "token",
    "msg" : "Invalid query parameter",
    "value" : null
  }, {
    "param" : "token",
    "msg" : "Invalid query parameter",
    "value" : null
  }, {
    "param" : "token",
    "msg" : "Invalid query parameter",
    "value" : null
  }, {
    "param" : "token",
    "msg" : "Invalid query parameter",
    "value" : null
  } ]
}
```
Is it my bad or something go wrong with service?

**Comment by nhoughto** [comment]
Had a major release over the weekend, so possible we have regressed. Investigating.

**Comment by nhoughto** [comment]
Fixed, will be deployed soon. Is available in the latest runtime binary.
