### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by dylanspurgin** [getsandbox/feedback#9]
Requests to our mocked auth endpoint (haven't checked others) are returning 400. We haven't made any changes to our sandbox or our login code (that we can see). This was working on Friday.

The request:
`curl 'http://api-mock.getsandbox.com/v1/auth' -X OPTIONS -H 'Pragma: no-cache' -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost:4567' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:4567/' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: accept, content-type, x-auth-token, x-ls-client' —compressed`

Gets a 400 response. Please advise. This is currently blocking our release process.

**Comment by nhoughto** [comment]
Fix has been rolled out, it appears OPTIONS requests were being processed incorrectly.
